apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: kubesail/app
      context: app
      sync: { manual: [{ src: app/**/*, dest: . }] }
deploy:
  kustomize: { paths: [overlays/dev] }
