apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels: { app: app }
spec:
  selector: { matchLabels: { app: app } }
  minReadySeconds: 1
  strategy: { type: Recreate }
  replicas: 1
  template:
    metadata: { labels: { app: app } }
    spec:
      terminationGracePeriodSeconds: 0
      imagePullSecrets: [{ name: dockerhub }]
      containers:
        - name: app
          image: kubesail/app
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-ports
              containerPort: 3000
            - name: metrics
              containerPort: 5000
          envFrom: [{ secretRef: { name: api } }]
          resources:
            requests: { cpu: 50m, memory: 100Mi }
            limits: { cpu: "2", memory: 1500Mi }
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-ports
    - port: 5000
      protocol: TCP
      targetPort: metrics
  selector: { app: app }
